DROP TABLE IF EXISTS tracktimes;
DROP TABLE IF EXISTS setups;
DROP TABLE IF EXISTS tracks;
DROP TABLE IF EXISTS platforms;
DROP TABLE IF EXISTS bodyshells;
DROP TABLE IF EXISTS types;
DROP TABLE IF EXISTS users;